title: d/place world
description: Enter the world of d/place, where anarchy reigns supreme and chaos is the only rule.
author: Skoopy Dev
url: https://dplace-world.github.io

favicon: "./dplace.png"

theme_config:
  appearance: "dark"
  appearance_toggle: true
  back_home_text: "back"
  date_format: "%Y/%m/%d"
  show_description: true
  show_navbar: true

navbar_entries:
  - title: home
    url: https://dplace-world.github.io

  - title: about
    url: https://dplace-world.github.io/about

  - title: history
    url: https://dplace-world.github.io/history

footer_entries:
  - title: skoopy's homepage
    url: https://skoopy.jased.xyz

remote_theme: abhinavs/moonwalk
plugins:
 - jekyll-remote-theme
