title: d/place world
description: Join the ultimate anarchy Discord server where chaos rules and everyone gets admin perms. Create, destroy, join factions or forge your path. Embrace the chaos!
theme: tactile
