title: d/place world
description: Enter the world of d/place, where anarchy reigns supreme and chaos is the only rule.
author: Skoopy Dev
url: https://dplace-world.github.io

favicon: "./favicon.ico"

theme_config:
  appearance: "auto" # "light", "dark" or "auto"
  appearance_toggle: true
  back_home_text: "back"
  date_format: "%Y/%m/%d"
  show_description: true
  show_navbar: true

remote_theme: abhinavs/moonwalk
plugins:
 - jekyll-remote-theme
